import ComposeApp
import SwiftUI
import UIKit

/// SwiftUI wrapper for hosting the Kotlin Multiplatform Compose `UIViewController`.
///
/// Implements [UIViewControllerRepresentable] to bridge the Compose `MainViewController()`
/// generated by the `composeApp` module into the SwiftUI view hierarchy.
struct ComposeView: UIViewControllerRepresentable {
    /// Creates and initializes the Compose Multiplatform UIViewController instance.
    ///
    /// - Parameter context: The representable context provided by SwiftUI.
    /// - Returns: The root [UIViewController] provided by `MainViewControllerKt.MainViewController()`.
    func makeUIViewController(context: Self.Context) -> UIViewController {
        MainViewControllerKt.MainViewController()
    }

    /// Updates the state of the specified UIViewController with new information from SwiftUI.
    ///
    /// - Parameters:
    ///   - uiViewController: The active UIViewController.
    ///   - context: The representable context provided by SwiftUI.
    func updateUIViewController(_ uiViewController: UIViewController, context: Self.Context) {}
}

/// Root SwiftUI View for the Joyvie iOS Application.
///
/// Embeds the [ComposeView] component and instructs it to ignore safe area bounds,
/// allowing Compose Multiplatform UI to manage full-screen layout rendering.
struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea()
    }
}